Spawn actors leaderboard
carla-simulator/ros-bridge pull request #426
Opened 2020-12-02 19:54 UTC by jbmag

- I couldn't run the _ros_bridge_, as the condition in _pseudo_actor_ on the uid was comparing _None_ to an _int_, in the case of the _world_info_ _pseudo_actor_. Not sure if I missed something, but I added a condition to skip this test if uid is None.
- As for the _carla_spawn_actor_ node, to merge _carla_infrastructure_ and _carla_ego_vehicle_, I'm not sure if it's what you had in mind @fpasch In particular, it should be able to spawn several vehicles from a json config file right? I also take the spawn position from the config file instead of a ros parameter, tell me if that's ok!

2020-12-03 08:46 UTC, fpasch reviewed
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @fpasch and @jbmag)

*[a discussion](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbgknh6aJosOU3fFrZ:-MNbgknh6aJosOU3fFr_:b-ctt2oo) (no related file):*
Please reuse the readme and adapt it to the new json format and features.
Please also state, that the default attributes can be overridden by specifying them in the json file (otherwise the default is used).

---
___
*[carla_spawn_actors/config/actors.json, line 10 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbeV84DSMsjKH94OCe:-MNbeV84DSMsjKH94OCf:b-69ix01) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/config/actors.json#L10)):*
> ```JSON
>             "image_size_x": 800,
>             "image_size_y": 600,
>             "fov": 100,
> ```

please add 
                    "sensor_tick": 0.05,
___
*[carla_spawn_actors/config/actors.json, line 11 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbe_tL-F5phQqExFGG:-MNbe_tL-F5phQqExFGH:bldopok) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/config/actors.json#L11)):*
<details><summary><i alt="summary">Quoted 35 lines of code…</i></summary>

> ```
>             "gamma": 2.2,
>             "shutter_speed": 60.0,
>             "iso": 100.0,
>             "fstop": 1.4,
>             "min_fstop": 1.2,
>             "blade_count": 5,
>             "exposure_mode": "histogram",
>             "exposure_compensation": 0.0,
>             "exposure_min_bright": 7.0,
>             "exposure_max_bright": 9.0,
>             "exposure_speed_up": 3.0,
>             "exposure_speed_down": 1.0,
>             "calibration_constant": 16.0,
>             "focal_distance": 1000.0,
>             "blur_amount": 1.0,
>             "blur_radius": 0.0,
>             "motion_blur_intensity": 0.45,
>             "motion_blur_max_distortion": 0.35,
>             "motion_blur_min_object_screen_size": 0.1,
>             "slope": 0.88,
>             "toe": 0.55,
>             "shoulder": 0.26,
>             "black_clip": 0.0,
>             "white_clip": 0.04,
>             "temp": 6500.0,
>             "tint": 0.0,
>             "chromatic_aberration_intensity": 0.0,
>             "chromatic_aberration_offset": 0.0,
>             "enable_postprocess_effects": "True",
>             "lens_circle_falloff": 5.0,
>             "lens_circle_multiplier": 0.0,
>             "lens_k": -1.0,
>             "lens_kcube": 0.0,
>             "lens_x_size": 0.08,
>             "lens_y_size": 0.08
> ```
</details>

please remove all these attributes, starting with gamma.
___
*[carla_spawn_actors/config/actors.json, line 60 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbejabECiEJRnqOige:-MNbejabECiEJRnqOigf:bja8zng) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/config/actors.json#L60)):*
<details><summary><i alt="summary">Quoted 37 lines of code…</i></summary>

> ```
>                     "gamma": 2.2,
>                     "shutter_speed": 200.0,
>                     "iso": 100.0,
>                     "fstop": 8.0,
>                     "min_fstop": 1.2,
>                     "blade_count": 5,
>                     "exposure_mode": "histogram",
>                     "exposure_compensation": 0.0,
>                     "exposure_min_bright": 7.0,
>                     "exposure_max_bright": 9.0,
>                     "exposure_speed_up": 3.0,
>                     "exposure_speed_down": 1.0,
>                     "calibration_constant": 16.0,
>                     "focal_distance": 1000.0,
>                     "blur_amount": 1.0,
>                     "blur_radius": 0.0,
>                     "motion_blur_intensity": 0.45,
>                     "motion_blur_max_distortion": 0.35,
>                     "motion_blur_min_object_screen_size": 0.1,
>                     "slope": 0.88,
>                     "toe": 0.55,
>                     "shoulder": 0.26,
>                     "black_clip": 0.0,
>                     "white_clip": 0.04,
>                     "temp": 6500.0,
>                     "tint": 0.0,
>                     "chromatic_aberration_intensity": 0.0,
>                     "chromatic_aberration_offset": 0.0,
>                     "enable_postprocess_effects": "True",
>                     "lens_circle_falloff": 5.0,
>                     "lens_circle_multiplier": 0.0,
>                     "lens_k": -1.0,
>                     "lens_kcube": 0.0,
>                     "lens_x_size": 0.08,
>                     "lens_y_size": 0.08,
>                     "bloom_intensity": 0.675,
>                     "lens_flare_intensity": 0.1
> ```
</details>

please remove all these attributes, starting with gamma.
___
*[carla_spawn_actors/config/actors.json, line 131 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNberYK3m5DoDLKWrqV:-MNberYK3m5DoDLKWrqW:bja8zng) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/config/actors.json#L131)):*
<details><summary><i alt="summary">Quoted 37 lines of code…</i></summary>

> ```
>                     "gamma": 2.2,
>                     "shutter_speed": 200.0,
>                     "iso": 100.0,
>                     "fstop": 8.0,
>                     "min_fstop": 1.2,
>                     "blade_count": 5,
>                     "exposure_mode": "histogram",
>                     "exposure_compensation": 0.0,
>                     "exposure_min_bright": 7.0,
>                     "exposure_max_bright": 9.0,
>                     "exposure_speed_up": 3.0,
>                     "exposure_speed_down": 1.0,
>                     "calibration_constant": 16.0,
>                     "focal_distance": 1000.0,
>                     "blur_amount": 1.0,
>                     "blur_radius": 0.0,
>                     "motion_blur_intensity": 0.45,
>                     "motion_blur_max_distortion": 0.35,
>                     "motion_blur_min_object_screen_size": 0.1,
>                     "slope": 0.88,
>                     "toe": 0.55,
>                     "shoulder": 0.26,
>                     "black_clip": 0.0,
>                     "white_clip": 0.04,
>                     "temp": 6500.0,
>                     "tint": 0.0,
>                     "chromatic_aberration_intensity": 0.0,
>                     "chromatic_aberration_offset": 0.0,
>                     "enable_postprocess_effects": "True",
>                     "lens_circle_falloff": 5.0,
>                     "lens_circle_multiplier": 0.0,
>                     "lens_k": -1.0,
>                     "lens_kcube": 0.0,
>                     "lens_x_size": 0.08,
>                     "lens_y_size": 0.08,
>                     "bloom_intensity": 0.675,
>                     "lens_flare_intensity": 0.1
> ```
</details>

please remove all these attributes, starting with gamma.
___
*[carla_spawn_actors/config/actors.json, line 187 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbf7PL-fz8Xe0sUILy:-MNbf7PM50PBbUaFD7LF:bbglbp9) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/config/actors.json#L187)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                     "lens_circle_falloff": 5.0,
>                     "lens_circle_multiplier": 0.0,
>                     "lens_k": -1.0,
>                     "lens_kcube": 0.0,
>                     "lens_x_size": 0.08,
>                     "lens_y_size": 0.08
> ```
</details>

please remove these attributes, starting with lens_circle_falloff
___
*[carla [...]

2020-12-03 09:08 UTC, fpasch reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @jbmag)

___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 165 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbmaxb68jAEoYAfncT:-MNbmaxb68jAEoYAfncU:brft6wm) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L165)):*
> ```Python
>             player = None
>             spawn_point = None
> ```

With Joel I discussed a change here. Our idea would be:
1. Check if a parameter for the spawn point is available: "<role_name>-spawn-point".  If yes, check if it has the right format "x,y,z,r,p,y". If not exit with error
2. If no parameter is available, check if the transform was specified within the json file (similar to a sensor position)
3. If still no transform is known, use a random one.
    - This should be achieved by adding a "random_spawn_point" field in the SpawnObject() service.
    - In the ros bridge the field should be checked and a random location should be calculated. Only walker and vehicles should be allowed to have a random spawn point. For 
      all others please report an error


<!-- Sent from Reviewable.io -->

2020-12-03 09:09 UTC, fpasch reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 3 of 9 files reviewed, 13 unresolved discussions (waiting on @jbmag)

___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 33 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNbrK4m9Gfnu3U0bDcB:-MNbrK4m9Gfnu3U0bDcC:b8kslt5) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L33)):*
> ```
> import carla
> ```
this should finally not be needed anymore


<!-- Sent from Reviewable.io -->

2020-12-03 18:48 UTC, jbmag commented
I think it should now be ready to merge, everything seems to be working. I also openned a PR in carla_msgs as I added a field in the SpawnObject server definition to be able to spawn vehicles at random locations.

2020-12-04 08:16 UTC, fpasch requested changes
> Reviewed 2 of 9 files at r1, 2 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @jbmag)

*[a discussion](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgoYY976oXJk36AtgG:-MNgoYY976oXJk36AtgH:b-6dbxqg) (no related file):*
Please also remove the carla_infrastructure and carla_ego_vehicle packages.

---
___
*[carla_spawn_actors/package.xml, line 14 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgigVLDaqWaEkvL1ow:-MNgigVM6eDUtV4Y8M7U:b-nddnae) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/package.xml#L14)):*
> ```XML
>   <exec_depend>rospy</exec_depend>
>   <exec_depend>topic_tools</exec_depend>
>   <export>
> ```

<exec_depend>carla_msgs</exec_depend>
___
*[carla_spawn_actors/README.md, line 3 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgilxIDPrjSqZppEa4:-MNgilxIDPrjSqZppEa5:b-2blne0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/README.md#L3)):*
> ```Markdown
> # carla_spawn_actors
> 
> TODO
> ```

please start with carla_ego_vehicle README and then adapt it
___
*[carla_spawn_actors/config/actors.json, line 16 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgiyMY42umTUq6cXhi:-MNgiyMY42umTUq6cXhj:bx8xzw6) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/config/actors.json#L16)):*
> ```JSON
>             "type": "vehicle.audi.tt",
>             "id": "ego_vehicle",
>             "spawn_point": {"x": 392.5, "y": -87.0, "z": 0.3, "roll": 0.0, "pitch": 0.0, "yaw": 90.0},
> ```

1. the default configuration should have an empty spawn point.
2. we should use a similar format for actor.spawn_point and sensor.spawn_point (currently sensor.x, sensor.y....). I would vote for spawn_point {}. @joel-mb what do you think?
___
*[carla_spawn_actors/launch/carla_spawn_actors.launch, line 33 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgm-BC1zHLIdQltLED:-MNgm-BD6Ypjb1PVgxqZ:bjwg3kd) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cb43bd76208104888c00540d3acd6338fa19ab93/carla_spawn_actors/launch/carla_spawn_actors.launch#L33)):*
> ```
> <param name="spawn_ego_vehicle" value="$(arg spawn_ego_vehicle)" />
> ```
We have to keep support for that. In this mode, only the attached sensors get spawned. Used e.g. with scenario runner. Scenario runner spawn all the vehicles and then this node should be able to attach all required sensors.
___
*[carla_spawn_actors/launch/carla_spawn_actors.launch, line 6 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgkIYa0CToqd0JlROX:-MNgkIYa0CToqd0JlROY:bc7cepf) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/launch/carla_spawn_actors.launch#L6)):*
> ```
>  <arg name="role_name" default="ego_vehicle"/>
> ```
should not be needed anymore.
___
*[carla_spawn_actors/launch/carla_spawn_actors.launch, line 9 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgkmR-9XUjye3lVCo9:-MNgkmR-9XUjye3lVCoA:bshnnay) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/launch/carla_spawn_actors.launch#L9)):*
> ```
> <arg name="spawn_point" default="392.5,-87.0,0.3,0.0,0.0,90.0"/>
> ```
As we now have support for spawning multiple actors, we cannot rely on *one* spawn_point.
Ideally it would be possible to specify "<ROLE NAME>-spawn-point" for whatever is defined in the json file.
In python that should be doable with get-param. Please check how that could be done in launch file (take the example json file with one ego-actor).
___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 15 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgjxa9B3s4B_0SdpLI:-MNgjxa9B3s4B_0SdpLJ:b13nh52) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L15)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - spawn at the pose read from ROS topic /initialpose
> Whenever a pose is received via /initialpose, the vehicle gets respawned at that
> position. If no /initialpose is set at startup, a random spawnpoint is used.
> /initialpose might be published via RVIZ '2D Pose Estimate" button.
> ```
</details>

please update.


<!-- Sent from Reviewable.io -->

2020-12-04 12:23 UTC, joel-mb requested changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 12 of 13 files reviewed, 12 unresolved discussions (waiting on @fpasch and @jbmag)

___
*[carla_spawn_actors/config/actors.json, line 16 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNgiyMY42umTUq6cXhi:-MNhgFA6907dcsDCMkXr:b2i0lfr) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/config/actors.json#L16)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

1. the default configuration should have an empty spawn point.
2. we should use a similar format for actor.spawn_point and sensor.spawn_point (currently sensor.x, sensor.y....). I would vote for spawn_point {}. @joel-mb what do you think?
</blockquote></details>

yeah, I vote to use the same format for sensors and vehicles (or any other actor). Using `spawn_point: {x: ..., y:, ..., ...}` seems the most appropriate. 
___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 50 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNhh0PhCLFmWvqj9tfx:-MNhh0PhCLFmWvqj9tfy:b-hxzodv) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f01596c02ed49d34acf2df45e3a2cd5dd892768b/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L50)):*
> ```
>         self.host = rospy.get_param('carla/host', '127.0.0.1')
>         self.port = rospy.get_param('carla/port', 2000)
>         self.timeout = rospy.get_param('carla/timeout', 10)
> ```
This is not needed anymore right? This node won't create any CARLA client.


<!-- Sent from Reviewable.io -->

2020-12-04 13:44 UTC, hofbi requested changes

2020-12-04 13:44 UTC, hofbi commented on carla_spawn_actors/CMakeLists.txt
> +roslaunch_add_file_check(launch IGNORE_UNSET_ARGS)
No to be consistent with the other packages you should change this line to 

```cmake
if(CATKIN_ENABLE_TESTING)
  roslaunch_add_file_check(launch)
endif()
```

2020-12-04 16:52 UTC, jbmag commented
Thanks for the reviews @fpasch, @joel-mb and @hofbi ! I changed and corrected what you asked!

2020-12-07 09:12 UTC, fpasch requested changes
> Reviewed 29 of 29 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 9 unresolved discussions (waiting on @jbmag)

___
*[carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch, line 32 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwKeoSCG9ARyXuZ8ob:-MNwKeoSCG9ARyXuZ8oc:bvsiy8t) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch#L32)):*
> ```
>   <!-- the ego vehicle, that will be controlled by the carla_ad_agent -->
> ```
That's not always valid. Please replace "by the carla_ad_agent" by "by an agent (e.g. carla_ad_agent)"
___
*[carla_spawn_actors/README.md, line 3 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwMFSk13xb9uzoF4Ey:-MNwMFSk13xb9uzoF4Ez:b-40p57q) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/README.md#L3)):*
> ```
> reference Carla client
> ```
please remove (it's not a carla-client anymore)
___
*[carla_spawn_actors/README.md, line 3 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwM_Ga6uBAfqxISg51:-MNwM_Ga6uBAfqxISg52:b-8w5jfo) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/README.md#L3)):*
> ```
> (vehicels,
> ```
typo
___
*[carla_spawn_actors/README.md, line 11 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwMxCA5K3qswu16mGp:-MNwMxCA5K3qswu16mGq:bwpvrn) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/README.md#L11)):*
> ```
> spawn_point_vehicle_name
> ```
please use spawn_point_<VEHICLE NAME>. and add an example at the end.
___
*[carla_spawn_actors/README.md, line 54 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwNcr74x0gVcYIvnQo:-MNwNcr74x0gVcYIvnQp:b-fxbbmo) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/README.md#L54)):*
> ```Markdown
> Define sensors with their attributes as described in the Carla Documentation about [Cameras and Sensors](https://github.com/carla-simulator/carla/blob/master/Docs/cameras_and_sensors.md).
> 
> An example is provided by [carla_example_ego_vehicle.launch](launch/carla_example_ego_vehicle.launch). It uses the sensors from [actors.json](config/actors.json)
> ```

please describe somewhere, that the attached sensors use a relative spawn_point.
___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 213 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwSoLKC853FsFcXI-U:-MNwSoLKC853FsFcXI-V:b-7hw8ke) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L213)):*
> ```
>  and sensor_type != "sensor.pseudo.actor_list":
> ```
is that needed?
___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 223 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwSqLD6a1KUjhFLKc7:-MNwSqLD6a1KUjhFLKc8:b-ikphaj) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L223)):*
> ```
> or is a 'sensor.pseudo.actor_list', 
> ```
see above


<!-- Sent from Reviewable.io -->

2020-12-07 09:40 UTC, jbmag commented
> _[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 213 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwSoLKC853FsFcXI-U:-MNwSoLKC853FsFcXI-V:b-7hw8ke) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L213)):_
> 
> > ```
> >  and sensor_type != "sensor.pseudo.actor_list":
> > ```
> 
> is that needed?
> 
> _[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 223 at r5](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNwSqLD6a1KUjhFLKc7:-MNwSqLD6a1KUjhFLKc8:b-ikphaj) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/1571494c1f95e23a51042a329639c3a4df3e13e6/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L223)):_
> 
> > ```
> > or is a 'sensor.pseudo.actor_list', 
> > ```
> 
> see above

I think so yes @fpasch :
   - In case of a global sensors you wanted an error when a spawn-point was not specified in the config file, so I cannot give default 0.0 values when I get the spawn point from the dictionary
   - In case of a sensor attached to a vehicle, I didn't think the previous point made sense as it's anyway a spawn-point relative to the vehicle, so a default (0.0, 0.0, 0.0) seemed quite logical...
   - and for the sensor.pseudo.actor_list, as it's a pseudo actor, I didn't think a a precise spawn_point was really important, and as this sensor is required to make the re-spawn mechanism work, I thought leaving a defualt (0.0, 0.0, 0.0) spawn-point simplified things for a user...

2020-12-07 11:41 UTC, fpasch approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 2 unresolved discussions (waiting on @jbmag)



<!-- Sent from Reviewable.io -->

2020-12-07 15:19 UTC, joel-mb requested changes
> Reviewed 2 of 9 files at r1, 1 of 3 files at r2, 1 of 7 files at r3, 21 of 29 files at r5, 5 of 6 files at r6, 2 of 2 files at r7, 6 of 6 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 6 unresolved discussions (waiting on @jbmag)

___
*[carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, line 47 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxeOrA48BHJMPQipDT:-MNxeOrA48BHJMPQipDU:b-1y9lxm) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py#L47)):*
> ```
>         self.parent = parent
>         self.node = node
> ```
duplicated
___
*[carla_spawn_actors/config/actors.json, line 2 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxizPE6GPR49-cWaXI:-MNxizPE6GPR49-cWaXJ:bpl3r8r) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L2)):*
> ```
>  "actors":·
> ```
Probably we want to include all the sensors and pseudo sensors that are described here: https://github.com/carla-simulator/ros-bridge/blob/leaderboard/carla_ego_vehicle/config/sensors.json and here: https://github.com/carla-simulator/ros-bridge/blob/leaderboard/carla_infrastructure/config/sensors.json with exactly the same ids to match the subscribed topic in the ad_agent package.
___
*[carla_spawn_actors/config/actors.json, line 24 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxlUA044GH7tiIM-Sh:-MNxlUA044GH7tiIM-Si:b-rc7jq2) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L24)):*
> ```
> "id": ""
> ```
Is this working? Right now, topic prefixes are structured as follows: `/carla/<PARENT_ID>/<SENSOR_ID>/<TOPIC_NAME>`. Probably, this is leading to something like this: `carla/ego_vehicle//set_transform`, which is not allowed. I would vote for moving the `initialpose` subscriber to the EgoVehicle object (https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py). @fpasch @jbmag what do you think?
___
*[carla_spawn_actors/launch/carla_example_ego_vehicle.launch, line 8 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxk9pM0mgaXp3GiROZ:-MNxk9pM0mgaXp3GiRO_:b-sqnuey) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/launch/carla_example_ego_vehicle.launch#L8)):*
> ```XML
>     and parameter name spawn_point_<vehicle_name>. You can add
>     as many spawn_point as vehicles defined in actors_definition_file-->
>   <arg name="spawn_point_ego_vehicle" default='"390.0,-87.0,0.3,0.0,0.0,90.0"'/>
> ```

Probably we want to remove this. Ideally, we should be able to use any map with this launch file.
___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 102 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxkj6083huzsOOll8z:-MNxkj6083huzsOOll9-:b-ln7hzr) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L102)):*
> ```
> actor_info_list = rospy.wait_for_message("/carla/actor_list", CarlaActorList)
> ```
I think it's better to create a service to this end (e.g., `GetActors`). In this way, we are not dependent on the actor_list pseudo sensor. @fpasch what do you think?


<!-- Sent from Reviewable.io -->

2020-12-07 15:25 UTC, joel-mb commented
@jbmag Also, Dockerfile and tests should be updated to accommodate the changes (i.e., remove dependencies on `carla_ego_vehicle` and `carla_infrastructure`

2020-12-07 15:30 UTC, fpasch reviewed
> Reviewed 5 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 40 of 41 files reviewed, 6 unresolved discussions (waiting on @fpasch, @jbmag, and @joel-mb)

___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 102 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxkj6083huzsOOll8z:-MNxnxYO8Vs6khu4xI1o:b-98ox5j) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L102)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> actor_info_list = rospy.wait_for_message("/carla/actor_list", CarlaActorList)
> ```
I think it's better to create a service to this end (e.g., `GetActors`). In this way, we are not dependent on the actor_list pseudo sensor. @fpasch what do you think?
</blockquote></details>

with having the map-reloading feature in our minds, I believe it makes more sense to have it as a topic. Of course for map reloading to work we would need to rework the implementation here to something like:
Whenever a spawned actor goes away (e.g. by reloading the map) respawn it.
(just as an idea....to be discussed)


<!-- Sent from Reviewable.io -->

2020-12-07 15:46 UTC, fpasch approved these changes
> Reviewed 1 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 6 unresolved discussions (waiting on @jbmag and @joel-mb)

___
*[carla_spawn_actors/config/actors.json, line 2 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxizPE6GPR49-cWaXI:-MNxp-m9EdbnUHilRtOB:bvt2oh5) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L2)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
>  "actors":·
> ```
Probably we want to include all the sensors and pseudo sensors that are described here: https://github.com/carla-simulator/ros-bridge/blob/leaderboard/carla_ego_vehicle/config/sensors.json and here: https://github.com/carla-simulator/ros-bridge/blob/leaderboard/carla_infrastructure/config/sensors.json with exactly the same ids to match the subscribed topic in the ad_agent package.
</blockquote></details>

that's a valid point.
___
*[carla_spawn_actors/config/actors.json, line 24 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxlUA044GH7tiIM-Sh:-MNxpES27QyJbawZrLn6:b-ddkd9i) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L24)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> "id": ""
> ```
Is this working? Right now, topic prefixes are structured as follows: `/carla/<PARENT_ID>/<SENSOR_ID>/<TOPIC_NAME>`. Probably, this is leading to something like this: `carla/ego_vehicle//set_transform`, which is not allowed. I would vote for moving the `initialpose` subscriber to the EgoVehicle object (https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py). @fpasch @jbmag what do you think?
</blockquote></details>

As "actor.pseudo.control" is already providing `set_transform` and `set_target_velocity` can we simply use "id": "control". Then we would have `/carla/ego_vehicle/control/set_transform`

As the initialpose feature is only used within a special use case (being able to move exactly one vehicle from within rviz) I would vote for the current setup, providing it within a separate ros node.
___
*[carla_spawn_actors/launch/carla_example_ego_vehicle.launch, line 8 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxk9pM0mgaXp3GiROZ:-MNxsLWv1qPp8gHQ0GK7:bhmeyp4) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/launch/carla_example_ego_vehicle.launch#L8)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

Probably we want to remove this. Ideally, we should be able to use any map with this launch file.
</blockquote></details>

True. Maybe we can have it commented out here.


<!-- Sent from Reviewable.io -->

2020-12-08 08:46 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 6 unresolved discussions (waiting on @fpasch, @jbmag, and @joel-mb)

___
*[carla_spawn_actors/config/actors.json, line 24 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxlUA044GH7tiIM-Sh:-MO0UT4h4gi45UCVQ-l2:b-gvu3n) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L24)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

As "actor.pseudo.control" is already providing `set_transform` and `set_target_velocity` can we simply use "id": "control". Then we would have `/carla/ego_vehicle/control/set_transform`

As the initialpose feature is only used within a special use case (being able to move exactly one vehicle from within rviz) I would vote for the current setup, providing it within a separate ros node.

</blockquote></details>

Using `control` as sensor id seems appropriate to me.
As the `initialpose` feature, I agree having it in a separate node. Maybe we can add a `control_id` parameter to the `set_intial_pose` launch file in order to make the id configurable?
___
*[carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py, line 102 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxkj6083huzsOOll8z:-MO0RpwyAgIr3KA1MHyb:b-rx804s) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/src/carla_spawn_actors/carla_spawn_actors.py#L102)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

with having the map-reloading feature in our minds, I believe it makes more sense to have it as a topic. Of course for map reloading to work we would need to rework the implementation here to something like:
Whenever a spawned actor goes away (e.g. by reloading the map) respawn it.
(just as an idea....to be discussed)
</blockquote></details>

I think both approaches should work well with map reloading but I agree some rework will be needed. We can leave it using the topic for now and see which solution is more appropriate in the future while working in the other functionalities. 
My point of using a service instead of a topic is to make things simpler. I believe that using a topic becomes tricky: the user has to spawn a global `sensor.pseudo.actor_list` with the specific `actor_list` id to make it work. I think that being able to spawn "sensors only" should work out of the box for any actors configuration file.  


<!-- Sent from Reviewable.io -->

2020-12-08 19:32 UTC, jbmag reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 33 of 45 files reviewed, 5 unresolved discussions (waiting on @fpasch, @jbmag, and @joel-mb)

___
*[carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, line 47 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxeOrA48BHJMPQipDT:-MO2oUgO3tKYIY8cjmLF:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py#L47)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
>         self.parent = parent
>         self.node = node
> ```
duplicated
</blockquote></details>

Done.
___
*[carla_spawn_actors/config/actors.json, line 2 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxizPE6GPR49-cWaXI:-MO2ofq78omxW5TWh5CS:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L2)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

that's a valid point.
</blockquote></details>

Done.
___
*[carla_spawn_actors/config/actors.json, line 24 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxlUA044GH7tiIM-Sh:-MO2ojPW5i8IH6jkFSPu:b-xsloca) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/config/actors.json#L24)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

Using `control` as sensor id seems appropriate to me.
As the `initialpose` feature, I agree having it in a separate node. Maybe we can add a `control_id` parameter to the `set_intial_pose` launch file in order to make the id configurable?
</blockquote></details>

Done, using a 'control_id' parameter to  make it configurable, as suggested, thanks!
___
*[carla_spawn_actors/launch/carla_example_ego_vehicle.launch, line 8 at r9](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MNxk9pM0mgaXp3GiROZ:-MO2p8Ov8o6362iJxffr:bgr2h1) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/3b5881d53d34c4c53ba3467a88d521c334db9e95/carla_spawn_actors/launch/carla_example_ego_vehicle.launch#L8)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

True. Maybe we can have it commented out here.
</blockquote></details>

I commented it.


<!-- Sent from Reviewable.io -->

2020-12-09 09:22 UTC, fpasch requested changes
> Reviewed 13 of 13 files at r11.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: 44 of 45 files reviewed, 7 unresolved discussions (waiting on @fpasch, @jbmag, and @joel-mb)

___
*[carla_spawn_actors/config/actors.json, line 25 at r11](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MO5m8DvBffucTIpIQ5L:-MO5m8DvBffucTIpIQ5M:b-eojogj) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/86a3bf7be7f7b1e61c12aa31dc5abf39b5a8d078/carla_spawn_actors/config/actors.json#L25)):*
> ```
> vehicle.audi.tt
> ```
It would be great if we could use "vehicle.*" here.
___
*[carla_spawn_actors/config/actors.json, line 37 at r11](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MO5mHmD4EgecyfarK_I:-MO5mHmD4EgecyfarK_J:b-4gsb3e) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/86a3bf7be7f7b1e61c12aa31dc5abf39b5a8d078/carla_spawn_actors/config/actors.json#L37)):*
<details><summary><i alt="summary">Quoted 37 lines of code…</i></summary>

> ```
>                     "gamma": 2.2,
>                     "shutter_speed": 200.0,
>                     "iso": 100.0,
>                     "fstop": 8.0,
>                     "min_fstop": 1.2,
>                     "blade_count": 5,
>                     "exposure_mode": "histogram",
>                     "exposure_compensation": 0.0,
>                     "exposure_min_bright": 7.0,
>                     "exposure_max_bright": 9.0,
>                     "exposure_speed_up": 3.0,
>                     "exposure_speed_down": 1.0,
>                     "calibration_constant": 16.0,
>                     "focal_distance": 1000.0,
>                     "blur_amount": 1.0,
>                     "blur_radius": 0.0,
>                     "motion_blur_intensity": 0.45,
>                     "motion_blur_max_distortion": 0.35,
>                     "motion_blur_min_object_screen_size": 0.1,
>                     "slope": 0.88,
>                     "toe": 0.55,
>                     "shoulder": 0.26,
>                     "black_clip": 0.0,
>                     "white_clip": 0.04,
>                     "temp": 6500.0,
>                     "tint": 0.0,
>                     "chromatic_aberration_intensity": 0.0,
>                     "chromatic_aberration_offset": 0.0,
>                     "enable_postprocess_effects": "True",
>                     "lens_circle_falloff": 5.0,
>                     "lens_circle_multiplier": 0.0,
>                     "lens_k": -1.0,
>                     "lens_kcube": 0.0,
>                     "lens_x_size": 0.08,
>                     "lens_y_size": 0.08,
>                     "bloom_intensity": 0.675,
>                     "lens_flare_intensity": 0.1
> ```
</details>

Please keep them removed. Same below.
___
*[carla_spawn_actors/src/carla_spawn_actors/set_initial_pose.py, line 34 at r11](https://reviewable.io/reviews/carla-simulator/ros-bridge/426#-MO5nX7I8VHgmK9bzJTP:-MO5nX7I8VHgmK9bzJTQ:bsa1iai) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/86a3bf7be7f7b1e61c12aa31dc5abf39b5a8d078/carla_spawn_actors/src/carla_spawn_actors/set_initial_pose.py#L34)):*
> ```
> rint("/carla/{}/{}/set_transform".format(self.role_name, self.control_id))
> ```
left over from debugging? If not, use valid logging.


<!-- Sent from Reviewable.io -->

2020-12-09 10:07 UTC, fpasch approved these changes
> Reviewed 4 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 4 unresolved discussions (waiting on @jbmag and @joel-mb)



<!-- Sent from Reviewable.io -->

2020-12-09 10:07 UTC, fpasch approved these changes
> Reviewed 5 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 4 unresolved discussions (waiting on @jbmag and @joel-mb)



<!-- Sent from Reviewable.io -->

2020-12-09 11:26 UTC, fpasch approved these changes
> Reviewed 19 of 20 files at r13.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/426)* status: all files reviewed, 4 unresolved discussions (waiting on @jbmag and @joel-mb)



<!-- Sent from Reviewable.io -->

2020-12-09 11:27 UTC, merged