Hybrid ROS1/ROS2 bridge
carla-simulator/ros-bridge pull request #441
Opened 2020-12-17 17:48 UTC by fpasch

2020-12-17 23:09 UTC, hofbi requested changes

2020-12-17 23:09 UTC, hofbi commented on .travis.yml
> +      addons:
All those additions in the travis file are probably in by accident. We already moved them to the github actions

2020-12-18 11:00 UTC, hofbi commented
I guess we need to setup a separate pipeline for ROS 2 in the CI. In the current way it fails as for ROS 2 the docker images are different than for ROS 1

2020-12-22 15:42 UTC, hofbi requested changes

2020-12-22 15:42 UTC, hofbi commented on packaging/build-deb.sh
> +if [ "$ROS_VERSION" = "noetic" -o "$ROS_VERSION" = "foxy" ]; then
I would rather test for not equal to "melodic". Then we don't need to change this for new ROS 2 versions

2020-12-22 15:42 UTC, hofbi commented on packaging/install_dependencies.sh
> +if [ "$ROS_VERSION" = "noetic" -o "$ROS_VERSION" = "foxy" ]; then
I would rather test for not equal to "melodic". Then we don't need to change this for new ROS 2 versions

2020-12-22 15:42 UTC, hofbi commented on packaging/install_dependencies.sh
> +if [ "$ROS_VERSION" = "foxy" ]; then
Here I would also use not equal to melodic or noetic to be more robust against changes

2020-12-22 15:42 UTC, hofbi commented on .github/workflows/ci.yml
>      - name: Build, Test, Lint
Now I would name with `ROS 2: Build, Test, Lint

2020-12-22 15:42 UTC, hofbi commented on .github/workflows/ci.yml
> +    - name: Build, Test, Lint
Now I would name with `ROS 1: Build, Test, Lint

2020-12-22 15:42 UTC, hofbi commented on .github/workflows/ci.yml
> +      if: matrix.ros-version != 'foxy'
To avoid the doubled check for ROS 1, we could put the code of the init workspace step into the ROS 1 build step

2021-03-04 17:21 UTC, fpasch reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/441)* status: 0 of 189 files reviewed, 1 unresolved discussion (waiting on @hofbi)

___
*[.travis.yml, line 29 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/441#-MOloP9sxMVO_aGj6Zfu-r1-29:-MUyFY_s9NarH0n4Aoi1:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f1a85a57b3d5eb59f1721cb49244dac7185a83c2/.travis.yml#L29)):*
<details><summary><i>Previously, hofbi (Markus Hofbauer) wrote…</i></summary><blockquote>

All those additions in the travis file are probably in by accident. We already moved them to the github actions
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-04 19:07 UTC, hofbi approved these changes

2021-03-22 11:15 UTC, joel-mb approved these changes
> Reviewed 1 of 184 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/441)* status: 1 of 193 files reviewed, 1 unresolved discussion (waiting on @hofbi)



<!-- Sent from Reviewable.io -->

2021-03-22 11:33 UTC, hofbi approved these changes

2021-03-22 11:40 UTC, joel-mb approved these changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/441)* status: 1 of 193 files reviewed, 1 unresolved discussion (waiting on @hofbi)



<!-- Sent from Reviewable.io -->

2021-03-22 16:42 UTC, joel-mb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/441#-:-MWPFcZq45HsqgIBxYPc:bnfp4nl)* status: 1 of 193 files reviewed, 1 unresolved discussion (waiting on @hofbi)



<!-- Sent from Reviewable.io -->

2021-03-22 16:51 UTC, merged