Corkyw10/ros documentation
carla-simulator/ros-bridge pull request #504
Opened 2021-03-09 10:00 UTC by corkyw10

# ROS documentation

I have created the documentation required to migrate ROS docs from the main CARLA project to it's own subproject.

- Uses the mkdocs readthedocs theme
- All packages have their own section
- Separate installation sections for ROS 1 and ROS 2
- Main ROS package explained in "Getting Started"

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)

2021-03-09 15:26 UTC, fpasch requested changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @corkyw10 and @joel-mb)

___
*[docs/carla_ackermann_control.md, line 1 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MVM_rSd2uzyCeOI1tpf:-MVM_rSd2uzyCeOI1tpg:bjdmjpa) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/86ff23be8d080d5b1154411b7b667b3d4831d92a/docs/carla_ackermann_control.md#L1)):*
> ```Markdown
> # Carla Ackermann Control
> ```

can we merge that somehow with carla_ackermann_control/README.md
(otherwise it will diverge).

that comment is valid for all the other functionality.


<!-- Sent from Reviewable.io -->

2021-03-09 16:02 UTC, hofbi commented
One possible solution to the feedback of @fpasch: Put all the content of the docs into the README of the specific node and use a symlink into the docs folder.

2021-03-09 16:42 UTC, corkyw10 commented
@hofbi Thanks for the input. I might not be understanding properly though, I don't know how I would create the symlink into the docs folder.

I have tried to see if mkdocs would let me link to the README through the mkdocs.yml file, but the page needs to be in the doc directory otherwise it returns a 404

2021-03-09 17:06 UTC, hofbi commented
You could something like this from the repo root folder (assuming you moved the content from the docs md file into the README and the docs md file is removed):

```shell
ln -s carla_ackermann_control/README.md docs/carla_ackermann_control.md
```

This should create a symlik from the README the the docs md file. Then you need to try the docs generation to see if this is supported. If not as the file need to be in the docs folder we could actually try the other way round symlinking from the docs md to the README

2021-03-10 09:59 UTC, hofbi commented
Then we would not require the symlinks, but keep the READMEs very small and directly link to the docs.

2021-03-10 10:11 UTC, fpasch commented
I agree with the idea of having the documentation in readthedocs only.
To keep things simple, I suggest we completely remove the sub-READMEs and have a minimal one in the root folder, that mainly links to readthedocs. But we should ensure somehow, that there is some kind of linkage between a ros-package/folder and the chapter in readthedocs and that *all* packages get documented.

2021-03-10 11:17 UTC, hofbi commented
So we could keep every README as this will automatically displayed by github in a nice ways, but every package README just contains the link to the docs.

2021-03-10 11:22 UTC, corkyw10 commented
I can add a button in each section of readthedocs linking to the packages in the repo, no problem with that. I can also change the READMEs and the links back to the docs there if you want, but that would be after making the documentation live. 

In terms of the packages all getting documented, I have made a section for each package that is listed on the current main README in the "Additional Functionality" section except for the walker agent because it was my understanding that it would be removed at some point. Are there other packages that I have missed and need included?

2021-03-17 14:50 UTC, corkyw10 commented
@fpasch @hofbi @joel-mb I have added sections for the twist to control and scenario runner packages. I have also made a link in each package section that links to the respective area of the repo

2021-03-22 17:49 UTC, joel-mb requested changes
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 1 of 25 files reviewed, 3 unresolved discussions (waiting on @corkyw10)

___
*[docs/carla_ackermann_control.md, line 14 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MWPvTZD5lhs85MAuuSA:-MWPvTZEDGbkV1iOaG1_:b-i503ex) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/c89e0a64c0c0ce33107c29089d85f4d8c273ad35/docs/carla_ackermann_control.md#L14)):*
> ```Markdown
> ---
> 
> ### Install the PID controller library
> ```

This section can be removed. The `simple-pid` library will now be installed using `rosdep`.
___
*[docs/carla_ackermann_control.md, line 25 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MWPwXfg8TrKU-CeON4q:-MWPwXfg8TrKU-CeON4r:b-u2bhvd) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/c89e0a64c0c0ce33107c29089d85f4d8c273ad35/docs/carla_ackermann_control.md#L25)):*
> ```
> during runtime via ROS [dynamic reconfigure][rosdynamicreconfig]
> ```
As far as I know the `dynamic reconfigure` package is not available for ROS2. So this only applies to ROS1.
I don't know of any tool to dynamically set ROS2 parameters via a GUI. @fpasch Do you have any idea?


<!-- Sent from Reviewable.io -->

2021-03-25 09:56 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 1 of 25 files reviewed, 3 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[docs/carla_ackermann_control.md, line 14 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MWPvTZD5lhs85MAuuSA:-MWco2G53FRZnepTS1lp:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/c89e0a64c0c0ce33107c29089d85f4d8c273ad35/docs/carla_ackermann_control.md#L14)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

This section can be removed. The `simple-pid` library will now be installed using `rosdep`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-30 09:51 UTC, joel-mb requested changes
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 2 of 25 files reviewed, 34 unresolved discussions (waiting on @corkyw10)

___
*[docs/carla_ackermann_control.md, line 23 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1LQ7n0YnZ5G6AMUMI:-MX1LQ7n0YnZ5G6AMUMJ:b-8d4ypw) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ackermann_control.md#L23)):*
> ```
> ### Available topics
> ```
I would try to keep the same structure for describing the ROS API for all the packages. I would for the following organization:

```
ROS API
- Parameters
parameter_name (datatype): Description (table)

- Subscribed Topics
topic_name (topic_type): Description (table)

- Published Topics
topic_name (topic_type): Description (table)

- Services
service_name (service_type): Description (table)
```
___
*[docs/carla_ad_agent.md, line 18 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1L_cZ39UZedr3FMUT:-MX1L_cZ39UZedr3FMUU:b-7mnsso) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ad_agent.md#L18)):*
> ```Markdown
> The PID parameters were gathered by [Ziegler-Nichols method](https://en.wikipedia.org/wiki/Ziegler%E2%80%93Nichols_method).
> 
> ## Publications and subscriptions
> ```

I think this should be the structure for documenting the API for all the packages. Just change the titles to the proper ones.
___
*[docs/carla_ad_demo.md, line 13 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1MhVf0FFyo056mGS9:-MX1MhVf0FFyo056mGSA:b-vsk47k) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ad_demo.md#L13)):*
> ```
> Make sure your Python path is configured correctly to point to the correct version of CARLA:
> ```sh
> export PYTHONPATH=$PYTHONPATH:<path_to_carla>/PythonAPI/carla-<carla_version_and_arch>.egg:<path_to_carla>/PythonAPI/carla/
> ```
> ```
I would remove this. As this is needed for all the packages I would place this in a more general section (maybe installation?)
___
*[docs/carla_manual_control.md, line 15 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Nq4I9TJsInfFYfo9:-MX1Nq4I9TJsInfFYfoA:bgku532) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L15)):*
> ```
> view
> ```
change this to `rgb_view`
___
*[docs/carla_manual_control.md, line 16 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1NuqJEElqgJq4KrZE:-MX1NuqJEElqgJq4KrZF:b-yiksur) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L16)):*
> ```
> gnss1
> ```
change this to `gnss`
___
*[docs/carla_manual_control.md, line 17 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1O3rk23l64BM8xtU3:-MX1O3rk23l64BM8xtU4:b-b91mer) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L17)):*
> ```
> a lane invasion sensor
> ```
a lane invasion sensor with role-name `lane_invasion`
___
*[docs/carla_manual_control.md, line 18 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1O9xd846qDNwFywEa:-MX1O9xd846qDNwFywEb:bp9w84z) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L18)):*
> ```
> a collision sensor
> ```
a collision sensor with role-name `collision`
___
*[docs/carla_manual_control.md, line 22 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1OaGY08hlT7nc2tjA:-MX1OaGY08hlT7nc2tjB:b-c45y) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L22)):*
> ```
> Run the package
> ```
At the end of this section I would also add that we provide a launch file to ease the execution of the manual control package. They just need to run:

```sh
#ROS1
roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch

#ROS2
ros2 launch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch.py
```
___
*[docs/carla_manual_control.md, line 37 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Q-xD95kgjSDAm9Hc:-MX1Q-xD95kgjSDAm9Hd:b-o5rt82) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L37)):*
> ```
> ········
> ```
trailing spaces
___
*[docs/carla_manual_control.md, line 38 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Q1uP3mNeDoK8nYp7:-MX1Q1uP3mNeDoK8nYp8:b-o5rt82) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L38)):*
> ```
> ········
> ```
trailing spaces
___
*[docs/carla_ros_scenario_runner.md, line 26 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1QHFw2ZVMYuKVVPIM:-MX1QHFxDwQG7IDAQWxo:bdisx35) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ros_scenario_runner.md#L26)):*
> ```
> Runer
> ```
Runner
___
*[docs/carla_ros_scenario_runner.md, line 52 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1QXYA-6t1NGJPtKJY:-MX1QXYA-6t1NGJPtKJZ:b-pevdzf) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ros_scenario_runner.md#L52)):*
> ```
> __1.__ Export the environment variables:
> ```sh
> export PYTHONPATH=$PYTHONPATH:<path_to_carla>/PythonAPI/carla-<carla_version_and_arch>.egg:<path_to_carla>/PythonAPI/carla/
> ```
> ```
I would remove this. We can keep this in the installation section.
___
*[docs/carla_ros_scenario_runner.md, line 77 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Qm7h2bIERU7Axm8w:-MX1Qm7h2bIERU7Axm8x:b-ve051r) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ros_scenario_runner.md#L77)):*
> ```
> Services and topics
> ```
Change to the proper titles. See above
___
*[docs/carla_spawn_objects.md, line 32 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1R0y83DsHIHEIC5Ks:-MX1R0y83DsHIHEIC5Kt:b-11text) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_spawn_objects.md#L32)):*
> ```
> ···
> ```
trailing spaces
___
*[docs/carla_spawn_objects.md, line 40 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1QzvF5fgoqQ5PgmXx:-MX1QzvF5fgoqQ5PgmXy:b-nkmb6p) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_spawn_objects.md#L40)):*
> ```
> ·······
> ```
trailing spaces
___
*[docs/carla_spawn_objects.md, line 101 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1RG_Z7IfKogHoP3Jh:-MX1RG_Z7IfKogHoP3Ji:bodhscu) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_spawn_objects.md#L101)):*
> ```
> ················
> ```
trailing spaces
___
*[docs/carla_spawn_objects.md, line 129 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1RPhK6ejFyfHA5XSE:-MX1RPhK6ejFyfHA5XSF:bodhscu) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_spawn_objects.md#L129)):*
> ```
> ················
> ```
trailing spaces
___
*[docs/carla_twist_to_control.md, line 5 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1RaJb-D3sOl1g0CI_:-MX1RaJb-D3sOl1g0CIa:b3u7nya) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_tw [...]

2021-03-31 15:46 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 2 of 25 files reviewed, 34 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[docs/carla_ackermann_control.md, line 23 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1LQ7n0YnZ5G6AMUMI:-MX7eEGN7KZJHRh-sxDL:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ackermann_control.md#L23)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ### Available topics
> ```
I would try to keep the same structure for describing the ROS API for all the packages. I would for the following organization:

```
ROS API
- Parameters
parameter_name (datatype): Description (table)

- Subscribed Topics
topic_name (topic_type): Description (table)

- Published Topics
topic_name (topic_type): Description (table)

- Services
service_name (service_type): Description (table)
```
</blockquote></details>

Done.
___
*[docs/carla_ad_agent.md, line 18 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1L_cZ39UZedr3FMUT:-MX7frHh5J0r-LRFTUQf:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ad_agent.md#L18)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

I think this should be the structure for documenting the API for all the packages. Just change the titles to the proper ones.
</blockquote></details>

Done.
___
*[docs/carla_ad_demo.md, line 13 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1MhVf0FFyo056mGS9:-MX7hzqt3dMoUa8fXLHx:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ad_demo.md#L13)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Make sure your Python path is configured correctly to point to the correct version of CARLA:
> ```sh
> export PYTHONPATH=$PYTHONPATH:<path_to_carla>/PythonAPI/carla-<carla_version_and_arch>.egg:<path_to_carla>/PythonAPI/carla/
> ```
> ```
I would remove this. As this is needed for all the packages I would place this in a more general section (maybe installation?)
</blockquote></details>

Done.
___
*[docs/carla_manual_control.md, line 15 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Nq4I9TJsInfFYfo9:-MX7iCs3C36AXeVzYef_:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L15)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> view
> ```
change this to `rgb_view`
</blockquote></details>

Done.
___
*[docs/carla_manual_control.md, line 16 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1NuqJEElqgJq4KrZE:-MX7iDCv2nf-mNMzmDpa:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L16)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> gnss1
> ```
change this to `gnss`
</blockquote></details>

Done.
___
*[docs/carla_manual_control.md, line 17 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1O3rk23l64BM8xtU3:-MX7iaWf2nhatKWTWS55:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L17)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> a lane invasion sensor
> ```
a lane invasion sensor with role-name `lane_invasion`
</blockquote></details>

Done.
___
*[docs/carla_manual_control.md, line 18 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1O9xd846qDNwFywEa:-MX7iar0-5V8aiWMelu5:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L18)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> a collision sensor
> ```
a collision sensor with role-name `collision`
</blockquote></details>

Done.
___
*[docs/carla_manual_control.md, line 22 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1OaGY08hlT7nc2tjA:-MX7jY3z0RJqgXNo8WNE:b-jm0vac) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L22)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Run the package
> ```
At the end of this section I would also add that we provide a launch file to ease the execution of the manual control package. They just need to run:

```sh
#ROS1
roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch

#ROS2
ros2 launch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch.py
```
</blockquote></details>

Done. This already existed but I have changed the sentence explaining it slightly so it's more apparent. 
___
*[docs/carla_manual_control.md, line 37 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Q-xD95kgjSDAm9Hc:-MX7kBZn9VwCTFZBWptG:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L37)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ········
> ```
trailing spaces
</blockquote></details>

Done.
___
*[docs/carla_manual_control.md, line 38 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Q1uP3mNeDoK8nYp7:-MX7kBp82J8dpEH-6RLs:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_manual_control.md#L38)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ········
> ```
trailing spaces
</blockquote></details>

Done.
___
*[docs/carla_ros_scenario_runner.md, line 26 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1QHFw2ZVMYuKVVPIM:-MX7kTOACUh_ozDeSoOV:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ros_scenario_runner.md#L26)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Runer
> ```
Runner
</blockquote></details>

Done.
___
*[docs/carla_ros_scenario_runner.md, line 52 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1QXYA-6t1NGJPtKJY:-MX7kSJH9EuRurO-rP5U:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ros_scenario_runner.md#L52)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> __1.__ Export the environment variables:
> ```sh
> export PYTHONPATH=$PYTHONPATH:<path_to_carla>/PythonAPI/carla-<carla_version_and_arch>.egg:<path_to_carla>/PythonAPI/carla/
> ```
> ```
I would remove this. We can keep this in the installation section.
</blockquote></details>

Done.
___
*[docs/carla_ros_scenario_runner.md, line 77 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1Qm7h2bIERU7Axm8w:-MX7fl_4-owgdxaSYAP8:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_ros_scenario_runner.md#L77)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Services and topics
> ```
Change to the proper titles. See above
</blockquote></details>

Done.
___
*[docs/carla_spawn_objects.md, line 32 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MX1R0y83DsHIHEIC5Ks:-MX7lyp1600ClocPEGDo:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/03a21de9b1be4c93a18e4a3c93ead0247587ef09/docs/carla_spawn_objects.md#L32)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ``` [...]

2021-04-07 08:05 UTC, joel-mb reviewed
> Reviewed 3 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 4 of 24 files reviewed, 3 unresolved discussions (waiting on @corkyw10 and @joel-mb)



<!-- Sent from Reviewable.io -->

2021-04-12 09:40 UTC, joel-mb requested changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 4 of 24 files reviewed, 9 unresolved discussions (waiting on @corkyw10)

___
*[docs/ros_installation_ros1.md, line 13 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4Oe9p7wwcer9QgRAH:-MY4Oe9q8D4ZZweL9fWu:b77fd4x) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/ros_installation_ros1.md#L13)):*
> ```Markdown
> 
> !!! Important
>     ROS is still [experimental](http://wiki.ros.org/noetic/Installation) for Windows. It has only been tested for Linux systems.
> ```

I would say just that the ROS bridge has not been yet tested in Windows and remove the first part of the sentence. I don't really know which is the status of ROS in windows right now.
___
*[docs/run_ros.md, line 24 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4MhYOBj4w7iKk6_8v:-MY4MhYOBj4w7iKk6_8w:b-buwwic) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L24)):*
> ```
> ROS
> ```
the CARLA ROS bridge
___
*[docs/run_ros.md, line 55 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4Mtex5K8cjF-4PsRJ:-MY4Mtex5K8cjF-4PsRK:b3q1dl5) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L55)):*
> ```
> carla_ros_bridge_with_rviz.launch
> ```
remove this one as this has been removed.
___
*[docs/run_ros.md, line 61 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4P5NqDC3gHndpaF3A:-MY4P5NqDC3gHndpaF3B:b-lfpa6s) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L61)):*
> ```
> Configuration settings can be modified in [`ros-bridge/carla_ros_bridge/config/settings.yaml`](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/config/settings.yaml)
> ```
Remove this part of the sentence. The `settings.yaml` file has been deprecated in the ROS2/ROS1 version. To modify the configuration you have to do it when calling the launch file. Example:

```
roslaunch carla_ros_bridge carla_ros_bridge.launch passive:=True
```

This can also be done within the launch file. This is already explained in the next paragraph. 
___
*[docs/run_ros.md, line 68 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4Nm6M3Ec11UAW7ksZ:-MY4Nm6M3Ec11UAW7ks_:b1jyopw) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L68)):*
> ```
> (default)
> ```
now, the default mode is synchronous mode. 
___
*[docs/run_ros.md, line 80 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4NS331sqrdto1Xmct:-MY4NS331sqrdto1Xmcu:b-xcabkx) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L80)):*
> ```
> Using the ROS bridge in synchronous mode
> ```
 Could you please add a comment similar to this one at the beginning of this sections:

The bridge operates by default in CARLA synchronous mode, waiting for all sensor data that is expected within the current frame to ensure reproducible results.
___
*[docs/run_ros.md, line 134 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4O5ffAHQx8w9ZXgbr:-MY4O5ffAHQx8w9ZXgbs:b-ebmb61) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L134)):*
> ```
> ROS bridge subscriptions, publications and services
> ```
Please, change to ROS API.


<!-- Sent from Reviewable.io -->

2021-04-12 14:49 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 4 of 25 files reviewed, 9 unresolved discussions (waiting on @corkyw10, @fpasch, and @joel-mb)

___
*[docs/carla_ackermann_control.md, line 1 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MVM_rSd2uzyCeOI1tpf:-MY4ZCfc3Tl5wR68iT8s:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/86ff23be8d080d5b1154411b7b667b3d4831d92a/docs/carla_ackermann_control.md#L1)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

can we merge that somehow with carla_ackermann_control/README.md
(otherwise it will diverge).

that comment is valid for all the other functionality.
</blockquote></details>

Done.
___
*[docs/ros_installation_ros1.md, line 13 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4Oe9p7wwcer9QgRAH:-MY4ZXa50_1Ygc_bgFoH:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/ros_installation_ros1.md#L13)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

I would say just that the ROS bridge has not been yet tested in Windows and remove the first part of the sentence. I don't really know which is the status of ROS in windows right now.
</blockquote></details>

Done.
___
*[docs/run_ros.md, line 24 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4MhYOBj4w7iKk6_8v:-MY4_aY58WVY9JPJFatC:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L24)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ROS
> ```
the CARLA ROS bridge
</blockquote></details>

Done.
___
*[docs/run_ros.md, line 55 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4Mtex5K8cjF-4PsRJ:-MY4_q9E75V6NBK71o28:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L55)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> carla_ros_bridge_with_rviz.launch
> ```
remove this one as this has been removed.
</blockquote></details>

Done.
___
*[docs/run_ros.md, line 61 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4P5NqDC3gHndpaF3A:-MY4jdcPC2U9UdusPOsP:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L61)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Configuration settings can be modified in [`ros-bridge/carla_ros_bridge/config/settings.yaml`](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/config/settings.yaml)
> ```
Remove this part of the sentence. The `settings.yaml` file has been deprecated in the ROS2/ROS1 version. To modify the configuration you have to do it when calling the launch file. Example:

```
roslaunch carla_ros_bridge carla_ros_bridge.launch passive:=True
```

This can also be done within the launch file. This is already explained in the next paragraph. 
</blockquote></details>

Done.
___
*[docs/run_ros.md, line 68 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4Nm6M3Ec11UAW7ksZ:-MY4jznJAYB3tU-SYdm0:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L68)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> (default)
> ```
now, the default mode is synchronous mode. 
</blockquote></details>

Done.
___
*[docs/run_ros.md, line 80 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4NS331sqrdto1Xmct:-MY51yB2B9vbjXYEnaI8:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L80)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Using the ROS bridge in synchronous mode
> ```
 Could you please add a comment similar to this one at the beginning of this sections:

The bridge operates by default in CARLA synchronous mode, waiting for all sensor data that is expected within the current frame to ensure reproducible results.
</blockquote></details>

Done.
___
*[docs/run_ros.md, line 134 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MY4O5ffAHQx8w9ZXgbr:-MY5Xbux-qN_c_0Lx4mJ:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/8e5fb99151d3652f33d12b6cd49ab7a83784cdb4/docs/run_ros.md#L134)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ROS bridge subscriptions, publications and services
> ```
Please, change to ROS API.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-13 09:29 UTC, fpasch reviewed
> Reviewed 4 of 23 files at r1, 1 of 11 files at r2, 9 of 15 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 18 of 24 files reviewed, 8 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[docs/carla_ackermann_control.md, line 25 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MWPwXfg8TrKU-CeON4q:-MY9XbRX0VS3W4WU9dyh:bskp9w5) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/c89e0a64c0c0ce33107c29089d85f4d8c273ad35/docs/carla_ackermann_control.md#L25)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> during runtime via ROS [dynamic reconfigure][rosdynamicreconfig]
> ```
As far as I know the `dynamic reconfigure` package is not available for ROS2. So this only applies to ROS1.
I don't know of any tool to dynamically set ROS2 parameters via a GUI. @fpasch Do you have any idea?
</blockquote></details>

In ros2 settings parameters during runtime is possible as a feature of the "Node", but I believe we didn't integrate the required callbacks yet. So yes, I would  document it as ROS1 only


<!-- Sent from Reviewable.io -->

2021-04-13 09:30 UTC, fpasch approved these changes

2021-04-13 10:14 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: 17 of 24 files reviewed, 8 unresolved discussions (waiting on @corkyw10, @fpasch, and @joel-mb)

___
*[docs/carla_ackermann_control.md, line 25 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/504#-MWPwXfg8TrKU-CeON4q:-MY9iJ_iE5gkJ02FsUJv:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/c89e0a64c0c0ce33107c29089d85f4d8c273ad35/docs/carla_ackermann_control.md#L25)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

In ros2 settings parameters during runtime is possible as a feature of the "Node", but I believe we didn't integrate the required callbacks yet. So yes, I would  document it as ROS1 only
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-13 10:35 UTC, joel-mb approved these changes
> Reviewed 8 of 23 files at r1, 1 of 11 files at r2, 8 of 15 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corkyw10)



<!-- Sent from Reviewable.io -->

2021-04-13 15:50 UTC, merged